target_container: "your_target_container_name"
mqtt_broker: "mqtt://mqtt_broker_address:1883"
mqtt_username: "your_mqtt_username"
mqtt_password: "your_mqtt_password"
mqtt_topic: "logs"
keywords:
  - "Version"
  - "Starting Server"
  - "Server Started"
  - "Player connected"
  - "Player disconnected"
