version: '3'
services:
  log-tailer:
    image: ghcr.io/djryan012/tailer-to-mqtt:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: log_tailer_container
    volumes:
      - ./config.yaml:/app/config.yaml
      - /home/user/TailerMqtt/config.yml:/usr/local/bin/config.yml:ro

  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    environment:
      - MQTT_USERNAME=your_mqtt_username
      - MQTT_PASSWORD=your_mqtt_password
