version: '3'

services:
  log_reader:
    image: ghcr.io/djryan012/tailer-to-mqtt:dev
    container_name: tailing-to-mqtt
    build:
      context: .
      dockerfile: Dockerfile
    environment:  # Define environment variables here
      - MQTT_BROKER_HOST=host_ip
      - MQTT_BROKER_PORT=host_port
      - MQTT_USERNAME=name
      - MQTT_PASSWORD=password
      - MQTT_TOPIC=Topic
      - CONTAINER_ID_TO_READ=number
      - KEYWORDS=2112,2140,keywords,error,warning
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock