version: '3'

services:
  log_reader:
    image: ghcr.io/djryan012/tailer-to-mqtt:dev
    container_name: tailing-to-mqtt
    build:
      context: .
      dockerfile: Dockerfile
    environment:  # Define environment variables here
      - MQTT_BROKER_HOST=host_ip
      - MQTT_BROKER_PORT=host_port
      - MQTT_USERNAME=name
      - MQTT_PASSWORD=password
      - MQTT_TOPIC=topic
      - CONTAINER_NAME_TO_READ=container_name
      - KEYWORDS=Starting Server,Version,Server started,Stopping server
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock