version: '3'
services:
  log-tailer:
    image: ghcr.io/djryan012/tailer-to-mqtt:bash
    container_name: tailer-to-mqtt

    environment:
      - MQTT_HOST=mqtt.eclipse.org
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - LOG_KEYWORD=Starting Server
      - TARGET_CONTAINER_NAME=bedrock_creative