name: Build and Push Docker Image

on:
  push:
    branches:
      - "bash"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Print Docker Version
      run: docker --version

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build --file ./Dockerfile --platform linux/amd64,linux/arm64 --tag ghcr.io/djryan012/tailer-to-mqtt:bash --push .
