name: Docker Image Build

on:
  push:
    branches:
      - python

jobs:
  build:
    runs-on: ubuntu-latest

<<<<<<< HEAD
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push ghcr.io/djryan012/tailer-to-mqtt:latest
=======
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: ubuntu-latest
        push: true
        tags: ghcr.io/djryan012/tailer-to-mqtt:latest
>>>>>>> b7bb8ec9d1fc0d20905a087214878b7f33a08787
