name: Docker Image CI

on:
  push:
    branches: [ "python" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: ubuntu-latest
        push: true
        tags: ghcr.io/djryan012/tailer-to-mqtt:latest
